services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ad-task-final-project-php-app
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - postgres
      - mongo
    environment:
      - APP_ENV=development

  postgres:
    image: postgres:14
    container_name: ad-task-final-project-postgres
    environment:
      POSTGRES_DB: ad_task_db
      POSTGRES_USER: poginisnopz   # This creates the user 'poginisnopz'
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:5
    container_name: ad-task-final-project-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=poginisnopz
      - MONGO_INITDB_ROOT_PASSWORD=password123
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  phpPgAdmin:
    image: dockage/phppgadmin
    container_name: ad-task-final-project-phpPgAdmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: postgres
      PMA_USER: poginisnopz
      PMA_PASSWORD: password123
    depends_on:
      - postgres

volumes:
  pgdata:
  mongodata:
